### ISSUE TITLE
Add functionality for regular expressions

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#93] opened 2022-05-25 09:34 UTC
While the terminal automatically parses and expands some regular expressions (e.g. `onyo rm shelf/laptop_*`), there are additional cases mentioned in the readme, which should be newly discussed, implemented and then documented in the correct form.

> Field Validation
> [...]
> Entries can be strings or, for more complex needs, any valid [Python Regular Expression](https://docs.python.org/3/library/re.html#regular-expression-syntax).
> Values are checked for reserved characters before they are checked against the validation strings/patterns.
> One can effectively disable validation for a field by adding .* to the corresponding validation list.

Nothing about this is true right now, `onyo new` checks fields depending on the template used (including default, when nothing is specified, see PR #92 ), the validation can not be ignored in the way discribed. Therefore I will safe the text here, and remove it from the current readme with PR #91.

**Comment by TobiasKadelka** [comment] 2022-05-25 09:53
After the way globbing is implemented and works is decided, the section about short vs long names and Globbing should be added to the readme and explain these.

**Comment by aqw** [comment] 2022-08-30 08:00
Is this a duplicate of #98 ?

**Comment by TobiasKadelka** [comment] 2022-08-30 08:21
No it is absolutely not!

The other is about regex to define keys in the validation file (e.g. defining `RAM: [numbers]MB` to say you allow `RAM: 1200MB`, but not `1200` or `12GB`), while this is about the code actually expanding regex in paths. The terminal does expand regex, but it is possible to call python from scripts and other programs with regex (e.g. the onyo pytests). In the case of the tests, I have to use `glob.glob` to expand the string `onyo mv user/* shelf/`, because the terminal does expand it, but the scripts do not use the terminal, thereby they error out.

That is why I think there should be some expantion of regex in the code itself.
I did not "just add glob", because when somebody would escape `str\*ing` per shell, the terminal might parse it to `str*ing`, and the scripts would expand it. I think there be some thoughts invested in how/when onyo should be called, and no matter how it is implemented, it should also be documented (even if just a line "if called from scripts, expand yourself" will be added to the docs).

**Closed** 2022-10-27 16:04 UTC
Labels: implementation
