### ISSUE TITLE
exclude subtrees for `get`

### ISSUE THREAD

**Issue by bpoldrack** [psyinfra/onyo#359] opened 2023-05-31 14:23 UTC
`get` should probably have the means to exclude subtrees (such as an `retired` or `lost` folder) from queries.

Usecase from #345 would be a query for devices with a manufacturer recall.

**Comment by TobiasKadelka** [comment] 2023-06-01 09:33
This should be done together with an implementation of:
- https://github.com/psyinfra/onyo/issues/259

**Comment by aqw** [comment] 2024-03-15 22:31
Duplicate of #518

**Closed** 2024-03-15 22:31 UTC
