### ISSUE TITLE
define commit message bodies

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#296] opened 2023-03-01 10:16 UTC
We have the other issue #295, which discusses how commit message headers should look like. While we decided on doing a lot of shortening for some of the messages, we want the bodies to have all the information in the long format, here I want to discuss how to do that.

Currently, the body whould be build out of two different parts:
- message-arguments (e.g. using multiple `-m <msg> <msg2> <msg3>`)
  - the first is the message header, all others will become the message body
- list of "files changed".

It was also discussed to add the "command which was run" to the end of the commit message body, but here I am not fully sure how to do that in a nice way.

**Comment by TobiasKadelka** [comment] 2023-03-02 11:11
To give a "run record", there where to ideas so far, I will post them here for later reflections and discussions.

One, that uses arguments after shell interpretation:
```
import sys, os
print os.path.basename(sys.argv[0]), sys.argv[1:]
```

And a second idea, which probably does just work when onyo is used by the CLI:
```
subprocess.run("history | tail -n 1").split()[1:]
```

**Comment by aqw** [comment] 2023-03-02 13:16
`fc` will be portable across all unices, and not rely on a shell built-in. Though it won't solve the non-interactive issue.

```
fc -l -n | tail -1
```

**Comment by TobiasKadelka** [comment] 2023-03-02 13:44
I updated my comment. I am wondering, if we might want to check if onyo is called by tty or not and act differently based on that?

Because of `onyo edit`, and also `onyo new --edit` this can't be fully re-runable, but maybe this would help getting a step closer. I also wonder, how that could work with `onyo new --tsv`, and ideas we had in the past regarding possible functions `onyo import/export`

**Comment by bpoldrack** [comment] 2023-04-25 13:13
@TobiasKadelka 

I'd like some clarification here.

> We have the other issue, which discusses how commit messages should look like.

Could you please link "the other" instead? Otherwise such an issue is of utility only for someone who was fully following everything in onyo at the time this issue was written. And even they may forget over time.

And generally:

What exactly is the aim here? Sounds like reproducibility, but is it really? And if it is: What for?

**Comment by TobiasKadelka** [comment] 2023-04-25 13:21
Thanks, you are right, and I added/edited the other issue (#295) into the initial message!

Yes, the idea is to have a "run-record" in commits of a repository so as to make it reproducable.

The problems we had so far are that block this idea:
- shell-expantion (e.g. python does not get what command was actually run)
- information from tables (e.g. `onyo new --tsv <table>`, the table would not be part of commit messsages, so not reproducable)
- When working with the API, no CLI commands would be run anyways

**Comment by bpoldrack** [comment] 2023-06-01 15:46
I'd like to come back to this in context of #370.
Currently the involved paths of a commit are put into the message (based on what is currently staged, which is why this is relevant for removing staging).

So, a somewhat vague notion of reproducibility and may be "auditability" (is that even a word?) seem to be the reason to record those paths in the message. I'd like to question that idea once more.

- As far as inspecting the history goes, this is redundant information to begin with, since paths affected by the commit are already on record.
- This also implies, that putting them into the message as well has the potential to make things worse WRT to inspection, because any, however miniscule, bug now has the potential to turn the message into a lie. We loose the one source of truth and have two instead.
- As far as this is about making it easier to read and obvious via `onyo history`, that is not necessarily a matter of the commit message but of how we call `git log` (tig shows the paths by default anyway).
- Reproducibility, especially w/o a concrete imagination of that replay works, needs the information on record. The paths are on record w/o being in the commit message.
- If we want a notion of inventory operations that is about locations and assets rather than paths like "Renamed location A/B to A/C" or "Moved asset X from A/B to C/D", we can have that, but it would need to be done from within a higher-level context of a command implementation rather than from git's idea of staged changes, I think.
- Lastly, I do wonder whether reproducibility really depends on recording onyo commands rather than atomic inventory operations. For example: `onyo new not/yet/existing/location/asset` and `onyo mkdir not/yet/existing/location` + `onyo new not/yet/existing/location/asset` are equivalent. But they would currently result in two different commits. They could instead result in the exact same commits (two in both cases). That would not reflect the exact calls that were made, but the atomic inventory operations that were applied. Isn't that even better?

**Comment by bpoldrack** [comment] 2023-06-01 16:07
May be an elaboration on the point of "inventory operations":

From my POV, onyo deals with locations (do we have a better name than location?) and assets. Both can be:
- created
- deleted
- moved
- renamed

In addition the metadata of an asset can be modified (yes, overlaps with renaming).

That's it as far as I'm aware. Any command boils down to those. Hence any command could have one commit per such operation. I think that would satisfy a (for me conceivable) desire for replay and inspection/audit quite well w/o the need to figure out what exactly was called how in order to achieve that.

**Comment by bpoldrack** [comment] 2023-06-05 13:23
Addition: @aqw pointed out that bulk operations should still be committed together for several reasons. Sheer history size is one, but also: There was a reason and purpose for that operation, that is likely best kept that way. Especially the second part I do agree on.

However, I'd still argue to record "inventory operations" rather than onyo commands. What's important for inspection (audit or not) and possible replay scenarios is what was done (and why, by whom, etc.) and not so much how exactly it was done. So, asset(s) created, location(s) renamed, things moved from .. to ..., etc.
The commands are just the means. And those means may change. We may have a bunch of convenience commands in the future, but they'd still boil down to the same operations and it doesn't matter whether one did something using this or that command. Current example: `new`. It can create directories in addition to the new asset(s). It doesn't matter for a replay or an inspection, that it was the  `new` command. What matters is, what assets where created and what folders were created. That would also still be valid if `new`'s behavior changed.

Recording the exact call, I think, is useful only for a stricter notion of reproducibility, that
- I suspect is not terribly useful for onyo
- requires wrapping the entire call anyway, which isn't really an option

So, some commit message appendix (not "instead", but in addition to user provided message), that lists the "operation" with relevant information is what I'd go for. Obviously in a human and machine readable way.

**Comment by TobiasKadelka** [comment] 2023-06-06 07:44
> And may be: Who did it and when?

This is, as far as I think, already fairly good captured in commit messages.

----

About the rest: I do agree in principal that the inventory operations make more sense than the exact calls.
I want to argue, however, that IMO "rm: asset" is just a brief form of writing "an asset was deleted".

If we would have some way to differentiate between places were stuff is stored, like `shelf/`, `retired/` and such, I could see a value to have "give: asset" and "take: asset" as messages, but since we do not have this, I feel again like "mv: asset" is a reasonable way to give exactly that information you mentioned above.

We do already not differentiate for example, if information for a new asset is given via template, table, or CLI, we just have a message "new: asset". And I think is is not helpful, to have the longer "create: " summerizing "new: ..." and "mkdir: ...", when our current version gives more information.

----

All of this is not to say that you are wrong, but I do not see any good way of improving the current stile of commit messages, that actually provides more information.
For the commit message bodies, there I think we want to add additional information and discuss how they should look like, but even there I am not fully sure what to add right now.

**Closed** 2023-10-20 11:33 UTC
